DROP DATABASE IF EXISTS arlservice;
DROP USER IF EXISTS `arl_service`@`%`;
CREATE DATABASE IF NOT EXISTS arlservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `arl_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `arlservice`.* TO `arl_service`@`%`;
FLUSH PRIVILEGES;